[theme]
base = "dark"
primaryColor = "#4ade80"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#ededf5"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[auth]
enabled = false
